baseURL = 'http://dataascode.io'
languageCode = 'en-us'
title = 'Data as code'
theme = "hugo-book"
contentDir = "content/en"

[markup.tableOfContents]
  startLevel = 1

[params]
  BookToC = true
  BookSection = 'docs'